### ISSUE TITLE
Laravel 5.6 issue

### ISSUE THREAD

**Issue by AEK-BKF** [alkoumi/laravel-hijri-date#4]
Salam Alikum,
I've installed this package, but it doesn't work ! Class Hijri doesn't exist.

**Comment by alkoumi** [comment]
عليكم السلام ورحمة الله وبركاته

if you can post your code, that we can analyze 
BUT, 

brother, be sure to import the path to the `Hijrj::class ` using use statement


Example 
```
<?php

namespace App\Http\Controllers;

use Alkoumi\LaravelHijriDate\Hijri;

class HomeController extends Controller
{
    public function getHijriDate()
    {
        return Hijri::DateShortFormat();
    }

 }
```



<img width="790" alt="Screen Shot 1441-05-10 at 8 23 37 PM" src="https://user-images.githubusercontent.com/10585943/71783549-4fc69d00-2ff9-11ea-8085-b353a5982ed4.png">

**Comment by ahmed-aliraqi** [comment]
@AEK-BKF What are you doing here? I find you in all the repositories that I visit 😂
