### ISSUE TITLE
تحويل الهجري الى ميلادي

### ISSUE THREAD

**Issue by raar4ever** [alkoumi/laravel-hijri-date#9]
سلام عليكم ورحمة الله وبركاته 
كيف يتم تحويل التاريخ الهجري الى ميلادي

**Comment by raar4ever** [comment]
ايضا هل هناك طريقة لحساب الفرق بين تاريخين هجرية مثال حساب العمر

**Comment by alkoumi** [comment]
عليكم السلام ورحمة الله وبركاته 
يا أهلًا بالغالي

عن طريق الدالة

`Hijri::DateToGregorianFromDMY('5', '6', '1442')`

تستقبل ٣ معاملات
1- Hijri  Day
2- Hijri Month
3- Hijri Year

`It will return the Georgian Date => "2021/1/18"`

آمل أن تكون الطريقة واضحة وبسيطة

**Comment by alkoumi** [comment]
بالنسبة لحساب الفرق بين تاريخين هجريين
فالأمر بسيط بمساعدة 

`Laravel Carbon`

هذا الكود البسيط يخدمك

`$birthDate = Hijri::DateToGregorianFromDMY('26', '4', '1401');`
   ` $birthDate = Carbon::createFromDate($birthDate);`
   ` $age = $birthDate->diffInYears(Carbon::now());`
    `return $age;`
